/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huangbin_test_diyimage_ImageUtilsJni */

#ifndef _Included_com_huangbin_test_diyimage_ImageUtilsJni
#define _Included_com_huangbin_test_diyimage_ImageUtilsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    toFilmJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_toFilmJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    sharpenImageJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_sharpenImageJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    toGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_toGray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    sketchImageJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_sketchImageJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    bianYuanJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_bianYuanJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    angulationJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_angulationJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    angulationBallJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_angulationBallJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    gauss_SmoothJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_gauss_1SmoothJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    polishJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_polishJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    daoZhiJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_daoZhiJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    addFrameJni
 * Signature: ([I[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_addFrameJni
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    miHongJni
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_miHongJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    lineChangeJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_lineChangeJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    grayFaZhiJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_grayFaZhiJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    windowJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_windowJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    exposureJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_exposureJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    magicMirrorJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_magicMirrorJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    swirlJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_swirlJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    fuDiaoJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_fuDiaoJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    bianYuanSharpJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_bianYuanSharpJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    addSaltAndPepperNoiseJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_addSaltAndPepperNoiseJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    addGauseNoiseJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_addGauseNoiseJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    addPoissonNoiseJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_addPoissonNoiseJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    middle_SmoothJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_middle_1SmoothJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    ave_SmoothJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_ave_1SmoothJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    move_SmoothJni
 * Signature: ([IIIFFI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_move_1SmoothJni
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    StrokeAreasJni
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_StrokeAreasJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    histogramFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_histogramFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    mosaicJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_mosaicJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    blendingJni
 * Signature: ([I[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_blendingJni
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    ChannelMixFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_ChannelMixFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    MaskFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_MaskFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SolarizeFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SolarizeFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    PosterizeFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_PosterizeFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    BoxBlurFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_BoxBlurFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    BumpFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_BumpFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    WaterFilterJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_WaterFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    LightFilterGrayJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_LightFilterGrayJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    LightFilterBlendJni
 * Signature: ([I[III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_LightFilterBlendJni
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SunzhaoJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SunzhaoJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SunyunJni
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SunyunJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    ColorChangeJni
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_ColorChangeJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SkinFilterJni
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SkinFilterJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    ZoomSwirlJni
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_ZoomSwirlJni
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    ImgFun
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_ImgFun
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    cvSmooth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_cvSmooth
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    setSourceImageJni
 * Signature: ([III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_setSourceImageJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    setMaskImageJni
 * Signature: ([III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_setMaskImageJni
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    getSourceImageJni
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_getSourceImageJni
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    Openlocalclassfier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_Openlocalclassfier
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    OpenPicture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_OpenPicture
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    Evaluate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_Evaluate
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    setImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_setImage
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    getImageWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_getImageWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    getImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_getImageHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    setOpenCvImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_setOpenCvImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    reComposition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_reComposition
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    template
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_template
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SalientRegionDetectorJni
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SalientRegionDetectorJni
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    SeamCarve
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_SeamCarve
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    mouseClickJni
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_mouseClickJni
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    GrabInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_GrabInit
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    setGrabRect
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_setGrabRect
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    GrabCut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_GrabCut
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    GrabreComposite
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_GrabreComposite
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    VisualBalance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_VisualBalance
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    Inpainting
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_Inpainting
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    GrabreCompositeAndResize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_GrabreCompositeAndResize
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    reCompositeAndResize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_reCompositeAndResize
  (JNIEnv *, jclass);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    addHeight
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_addHeight
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_huangbin_test_diyimage_ImageUtilsJni
 * Method:    beautiFaceJni
 * Signature: ([IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_huangbin_test_diyimage_ImageUtilsJni_beautiFaceJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
