package com.huangbin.test.diyimage;

public class ImageUtilsJni {
	static{ 
    	System.loadLibrary("ImageUtilsJni"); 
    	//System.loadLibrary("opencv"); 
    	}
	public static native int[] toFilmJni(int[] pixels,int w,int h);
	public static native int[] sharpenImageJni(int[] pixels,int w,int h);
	public static native int[] toGray(int[] pixels,int w,int h);
	public static native int[] sketchImageJni(int[] pixels,int w,int h);
	public static native int[] bianYuanJni(int[] pixels,int w,int h);
	public static native int[] angulationJni(int[] pixels,int w,int h);
	public static native int[] angulationBallJni(int[] pixels,int w,int h);
	public static native int[] gauss_SmoothJni(int[] pixels,int w,int h);
	public static native int[] polishJni(int[] pixels,int w,int h);
	public static native int[] daoZhiJni(int[] pixels,int w,int h);
	public static native int[] addFrameJni(int[] dstpixels,int[] framepixels,int w,int h,int flag);
	public static native int[] miHongJni(int[] pixels,int w,int h,int sharpflag);
	public static native int[] lineChangeJni(int[] pixels,int w,int h);
	public static native int[] grayFaZhiJni(int[] pixels,int w,int h);
	public static native int[] windowJni(int[] pixels,int w,int h);
	public static native int[] exposureJni(int[] pixels,int w,int h);
	public static native int[] magicMirrorJni(int[] pixels,int w,int h);
	public static native int[] swirlJni(int[] pixels,int w,int h);
	public static native int[] fuDiaoJni(int[] pixels,int w,int h);
	public static native int[] bianYuanSharpJni(int[] pixels,int w,int h);
	public static native int[] addSaltAndPepperNoiseJni(int[] pixels,int w,int h);
	public static native int[] addGauseNoiseJni(int[] pixels,int w,int h);
	public static native int[] addPoissonNoiseJni(int[] pixels,int w,int h);
	public static native int[] middle_SmoothJni(int[] pixels,int w,int h);
	public static native int[] ave_SmoothJni(int[] pixels,int w,int h);
	public static native int[] move_SmoothJni(int[] pixels,int w,int h,float distance,float zoom,int angel);
	public static native int[] StrokeAreasJni(int[] pixels,int w,int h,int size);
	public static native int[] histogramFilterJni(int[] pixels,int w,int h);
	public static native int[] mosaicJni(int[] pixels,int w,int h);
	public static native int[] blendingJni(int[] firpixels,int[] sndpixels,int w,int h,int flag);
	public static native int[] ChannelMixFilterJni(int[] pixels,int w,int h);
	public static native int[] MaskFilterJni(int[] pixels,int w,int h);
	public static native int[] SolarizeFilterJni(int[] pixels,int w,int h);
	public static native int[] PosterizeFilterJni(int[] pixels,int w,int h);
	public static native int[] BoxBlurFilterJni(int[] pixels,int w,int h);
	public static native int[] BumpFilterJni(int[] pixels,int w,int h);
	public static native int[] WaterFilterJni(int[] pixels,int w,int h);
	public static native int[] LightFilterGrayJni(int[] pixels,int w,int h);
	public static native int[] LightFilterBlendJni(int[] srcpixels,int[] graypixels,int w,int h);
	public static native int[] SunzhaoJni(int[] pixels,int w,int h);
	public static native int[] SunyunJni(int[] pixels,int w,int h);
	public static native int[] ColorChangeJni(int[] pixels,int w,int h,int flag);
	public static native int[] SkinFilterJni(int[] pixels,int w,int h,int flag);
	public static native int[] ZoomSwirlJni(int[] pixels,int w,int h,float scale);
	public static native int[] ImgFun(int[] buf, int w, int h);
	public static native void cvSmooth();
	public static native boolean setSourceImageJni(int[] buf, int w, int h);
	public static native boolean setMaskImageJni(int[] buf, int w, int h);
	public static native int[] getSourceImageJni();
	public static native int Openlocalclassfier();
	public static native int OpenPicture();
	public static native String Evaluate();
	public static native void setImage();
	public static native int getImageWidth();
	public static native int getImageHeight();
	public static native int setOpenCvImage(String path);
	public static native int reComposition();
	public static native int[] template(int flags);
	public static native int SalientRegionDetectorJni(int sigmaS,float sigmaR);
	public static native int SeamCarve(int width,int height);
	public static native void mouseClickJni( int event, int x, int y, int flags);
	public static native int GrabInit();
	public static native int setGrabRect(int left,int top,int right,int bottom);
	public static native int GrabCut();
	public static native int GrabreComposite();
	public static native int VisualBalance();
	public static native int Inpainting();
	public static native int GrabreCompositeAndResize();
	public static native int reCompositeAndResize();
	public static native void addHeight(int seamnum,int lowheight,int highheight);
	public static native int[]beautiFaceJni(int []pixels,int x,int y,int w,int h,int flag);
}
